import React, { useState } from "react";
import { BarChart3, Check, FileSpreadsheet, FileText, Upload, X } from "lucide-react";

const formats = [["PDF", "Best for printing and sharing", FileText, "pdf"], ["Excel", "Best for data analysis and calculations", FileSpreadsheet, "excel"], ["Word", "Best for editable documents", FileText, "word"]];

export default function ExportModal({ reportName, onClose, onDateClick, dateRange }) {
  const [format, setFormat] = useState("pdf");
  const [includeCharts, setIncludeCharts] = useState(true);
  return <div className="export-overlay" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="export-modal" role="dialog" aria-modal="true" aria-labelledby="export-title"><div className="export-modal-header"><div><h2 id="export-title">Export Report</h2><p>Choose a format to export your {reportName.toLowerCase()} report. The file will include all the visible data in the current view.</p></div><button className="export-close" onClick={onClose} aria-label="Close export dialog"><X size={17} /></button></div><div className="export-formats">{formats.map(([label, description, Icon, value]) => <button className={`export-format ${format === value ? "selected" : ""}`} key={value} onClick={() => setFormat(value)}><span className={`format-icon ${value}`}><Icon size={22} /></span><strong>{label}</strong><small>{description}</small>{format === value && <i><Check size={11} /></i>}</button>)}</div><div className="export-options-title">Export Options</div><div className="export-options"><button className="export-select" onClick={onDateClick}><span>▣ &nbsp; 12 Sept - 20 Sept</span><span>⌄</span></button><button className="export-select"><span>☷ &nbsp; All Status</span><span>⌄</span></button></div><label className="chart-option"><input type="checkbox" checked={includeCharts} onChange={(event) => setIncludeCharts(event.target.checked)} /><BarChart3 size={14} /> Include chart data in report</label><div className="export-footer"><button className="secondary-btn" onClick={onClose}>Cancel</button><button className="primary-btn" onClick={onClose}><Upload size={14} /> Export {format === "excel" ? "Excel" : format === "word" ? "Word" : "Report"}</button></div></section></div>;
}
