import React, { useState } from "react";
import { CheckCircle2, ChevronRight, Cloud, CreditCard, Mail, MessageSquare, Package, Plug, RefreshCw, Truck } from "lucide-react";

const initialIntegrations = [["Stripe", "Accept card payments securely from your customers.", CreditCard, "Payments", true, "Connected"], ["Shiprocket", "Automate shipping and track every delivery.", Truck, "Shipping", true, "Connected"], ["Mailchimp", "Send campaigns and keep customers engaged.", Mail, "Marketing", false, "Not connected"], ["WhatsApp Business", "Send order updates and customer messages.", MessageSquare, "Communication", false, "Not connected"], ["Google Drive", "Back up reports and export files automatically.", Cloud, "Storage", false, "Not connected"], ["Inventory Sync", "Keep stock levels synchronized across channels.", RefreshCw, "Operations", false, "Not connected"]];
export default function IntegrationsPage() {
  const [items, setItems] = useState(initialIntegrations);
  const [category, setCategory] = useState("All categories");
  const toggle = (name) => setItems((current) => current.map((item) => item[0] === name ? [...item.slice(0, 5), !item[4], item[4] ? "Not connected" : "Connected"] : item));
  const visibleItems = items.filter((item) => category === "All categories" || item[3] === category);
  return <section className="admin-page integrations-page"><div className="admin-page-header"><div><h1>Integrations</h1><p>Connect the tools that power your store operations</p></div><button className="secondary-btn"><Plug size={15} /> Browse Apps</button></div><div className="integration-banner"><div className="banner-icon"><Package size={21} /></div><div><strong>Extend your workflow</strong><span>Connect trusted services to automate payments, shipping, marketing, and more.</span></div><button className="primary-btn">Explore integrations <ChevronRight size={14} /></button></div><div className="integration-heading"><div><h2>Connected Services</h2><p>Manage your active and available integrations</p></div><div className="integration-controls"><select value={category} onChange={(event) => setCategory(event.target.value)}><option>All categories</option><option>Payments</option><option>Shipping</option><option>Marketing</option><option>Communication</option><option>Storage</option><option>Operations</option></select><span><CheckCircle2 size={15} /> {items.filter((item) => item[4]).length} connected</span></div></div><div className="integration-grid">{visibleItems.map(([name, description, Icon, itemCategory, connected]) => <article className="integration-card card" key={name}><div className="integration-card-head"><div className="integration-icon"><Icon size={21} /></div><span className={connected ? "connected-pill" : "available-pill"}>{connected ? "Connected" : "Available"}</span></div><small>{itemCategory}</small><h3>{name}</h3><p>{description}</p><button className={connected ? "secondary-btn" : "primary-btn"} onClick={() => toggle(name)}>{connected ? "Manage" : "Connect"} <ChevronRight size={14} /></button></article>)}</div></section>;
}
