import React, { useState } from "react";
import { CheckCircle2, MoreVertical, Plus, Search, ShieldCheck, UserPlus, Users as UsersIcon } from "lucide-react";
import ActionMenu from "./ActionMenu";

const starterUsers = [["Ayush", "admin@gmail.com", "Super Admin", "Active", "AY"], ["Sara Williams", "sara@bloomstore.com", "Admin", "Active", "SW"], ["John Doe", "john@bloomstore.com", "Order Manager", "Active", "JD"], ["Nina Patel", "nina@bloomstore.com", "Editor", "Inactive", "NP"]];
export default function UsersPage() {
  const [query, setQuery] = useState("");
  const [role, setRole] = useState("All roles");
  const [status, setStatus] = useState("All statuses");
  const [users, setUsers] = useState(starterUsers);
  const filtered = users.filter((user) => user.join(" ").toLowerCase().includes(query.toLowerCase()) && (role === "All roles" || user[2] === role) && (status === "All statuses" || user[3] === status));
  return <section className="admin-page"><div className="admin-page-header"><div><h1>Users</h1><p>Manage team members and control their access</p></div><button className="primary-btn" onClick={() => setUsers((items) => [...items, [`New User ${items.length + 1}`, "newuser@bloomstore.com", "Editor", "Active", "NU"]])}><UserPlus size={15} /> Add User</button></div><div className="user-stats"><div className="stat-card card"><UsersIcon size={18} /><span>Total Users<strong>{users.length}</strong><small>Across all roles</small></span></div><div className="stat-card card"><CheckCircle2 size={18} /><span>Active Users<strong>{users.filter((user) => user[3] === "Active").length}</strong><small>Currently enabled</small></span></div><div className="stat-card card"><ShieldCheck size={18} /><span>Roles Assigned<strong>4</strong><small>Access profiles</small></span></div></div><section className="user-table-card card"><div className="table-toolbar"><div><h2>Team Members</h2><p>View and manage everyone with dashboard access</p></div><div className="user-filters"><div className="category-search"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search users..." /></div><select value={role} onChange={(event) => setRole(event.target.value)}><option>All roles</option><option>Super Admin</option><option>Admin</option><option>Order Manager</option><option>Editor</option></select><select value={status} onChange={(event) => setStatus(event.target.value)}><option>All statuses</option><option>Active</option><option>Inactive</option></select></div></div><div className="user-table"><div className="user-row user-head"><span>User</span><span>Role</span><span>Status</span><span>Last Active</span><span>Action</span></div>{filtered.map(([name, email, userRole, userStatus, initials]) => <div className="user-row" key={email}><span className="user-identity"><i>{initials}</i><b>{name}<small>{email}</small></b></span><span>{userRole}</span><span><em className={userStatus === "Active" ? "user-status active" : "user-status inactive"}>{userStatus}</em></span><span>Today, 10:24 AM</span><button className="table-action" aria-label={`Actions for ${name}`}><MoreVertical size={17} /></button></div>)}</div></section></section>;
}
